//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment_of_category
    {
        public string Type_treatment_Number { get; set; }
        public string Category_Number { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual Type_Treatment Type_Treatment { get; set; }
        public virtual Type_Treatment Type_Treatment1 { get; set; }
    }
}
